version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB = tool_manager
      - POSTGRES_USER = tool_manager_user
      - POSTGRES_PASSWORD = secret_password
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:800
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db