# Generated by Django 4.2.3 on 2024-03-14 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("machines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Author of the machine",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="description",
            field=models.TextField(help_text="Machine description"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="name",
            field=models.CharField(help_text="Machine name", max_length=100),
        ),
    ]
