# Generated by Django 4.2.3 on 2024-03-14 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("holders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holder",
            name="DH1_A",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="First outside diameter of the first holder segment",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="holder",
            name="DH1_B",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Second outside diameter of the first holder segment",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="holder",
            name="DH2",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Outside diameter of the second holder segment",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="holder",
            name="DH3",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Outside diameter of the third holder segment",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="holder",
            name="LH1",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text="Length of the first holder segment", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="holder",
            name="LH2",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text="Length of the second holder segment", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="holder",
            name="LH3",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text="Length of the third holder segment", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="holder",
            name="author",
            field=models.ForeignKey(
                default=None,
                help_text="Author of the holder",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="holder",
            name="catalog_nr",
            field=models.CharField(blank=True, help_text="Holder catalog number", max_length=100),
        ),
        migrations.AlterField(
            model_name="holder",
            name="holder_type",
            field=models.CharField(
                choices=[
                    ("type_1", "SLIM_100"),
                    ("type_2", "SLIM_150"),
                    ("type_3", "SLIM_200"),
                    ("type_4", "TERMO_100"),
                    ("type_5", "TERMO_150"),
                    ("type_6", "TERMO_200"),
                    ("type_7", "ER_32"),
                    ("type_8", "ER_40"),
                    ("type_9", "WELDON_100"),
                    ("type_10", "WELDON_150"),
                    ("type_11", "WELDON_200"),
                    ("type_12", "STYROPIAN"),
                    ("type_13", "UCHWYT_76"),
                ],
                help_text="Holder type",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="holder",
            name="inner_diameter",
            field=models.PositiveIntegerField(help_text="Inner diameter of the holder"),
        ),
    ]
