# Generated by Django 4.2.3 on 2023-10-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_assembly', '0002_remove_tool_author_alter_toolassembly_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolassembly',
            name='tool_nr',
            field=models.PositiveIntegerField(),
        ),
    ]
