# Generated by Django 4.2.3 on 2023-10-29 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools_assembly", "0005_alter_toolassembly_author_alter_usercomment_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercomment",
            old_name="toolassembly",
            new_name="tool_assembly",
        ),
    ]
