# Generated by Django 4.2.3 on 2023-09-30 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('end_mill', 'WALEC'), ('ball_nose', 'KULA'), ('bull_nose', 'WALEC_Z_R'), ('typer_ball_nose', 'STOZKOWY'), ('engraving', 'GRAWERKA'), ('drill', 'WIERTŁO')], max_length=100)),
                ('catalog_nr', models.CharField(max_length=100)),
                ('R', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('L1', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('D1', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('L2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('D2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('L3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('D3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('L4', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('D4', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
