# Generated by Django 4.2.3 on 2024-03-14 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="D1",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text="Blade diameter", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="D2",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text="Diameter of the first shaft segment", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="D3",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text="Diameter of the second shaft segment", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="D4",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text="Diameter of the third shaft segment", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="L1",
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Blade length", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="L2",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text="Length of the first shaft segment", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="L3",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text="Length of the second shaft segment", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="L4",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text="Length of the third shaft segment", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="R",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Corner radius of a end- and bull- mill",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="author",
            field=models.ForeignKey(
                default=None,
                help_text="Author of the tool",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="catalog_nr",
            field=models.CharField(help_text="Tool catalog number", max_length=100),
        ),
        migrations.AlterField(
            model_name="tool",
            name="tool_type",
            field=models.CharField(
                choices=[
                    ("end_mill", "WALEC"),
                    ("ball_nose", "KULA"),
                    ("bull_nose", "WALEC_Z_R"),
                    ("typer_ball_nose", "STOZKOWY"),
                    ("engraving", "GRAWERKA"),
                    ("drill", "WIERTŁO"),
                ],
                help_text="Tool type",
                max_length=100,
            ),
        ),
    ]
