# Generated by Django 4.2.3 on 2023-09-05 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_type', models.CharField(choices=[('type_1', 'SLIM_100'), ('type_2', 'SLIM_150'), ('type_3', 'SLIM_200'), ('type_4', 'TERMO_100'), ('type_5', 'TERMO_150'), ('type_6', 'TERMO_200'), ('type_7', 'ER_32'), ('type_8', 'ER_40'), ('type_9', 'WELDON_100'), ('type_10', 'WELDON_150'), ('type_11', 'WELDON_200'), ('type_12', 'STYROPIAN'), ('type_13', 'UCHWYT_76')], max_length=100)),
                ('inner_diameter', models.PositiveIntegerField()),
                ('catalog_nr', models.CharField(blank=True, max_length=100)),
                ('LH1', models.FloatField(blank=True, null=True)),
                ('DH1_A', models.FloatField(blank=True, null=True)),
                ('DH1_B', models.FloatField(blank=True, null=True)),
                ('LH2', models.FloatField(blank=True, null=True)),
                ('DH2', models.FloatField(blank=True, null=True)),
                ('LH3', models.FloatField(blank=True, null=True)),
                ('DH3', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('end_mill', 'WALEC'), ('ball_nose', 'KULA'), ('bull_nose', 'WALEC_Z_R'), ('typer_ball_nose', 'STOZKOWY'), ('engraving', 'GRAWERKA'), ('drill', 'WIERTŁO')], max_length=100)),
                ('catalog_nr', models.CharField(max_length=100)),
                ('R', models.PositiveIntegerField(blank=True, null=True)),
                ('L1', models.FloatField(blank=True, null=True)),
                ('D1', models.FloatField(blank=True, null=True)),
                ('L2', models.FloatField(blank=True, null=True)),
                ('D2', models.FloatField(blank=True, null=True)),
                ('L3', models.FloatField(blank=True, null=True)),
                ('D3', models.FloatField(blank=True, null=True)),
                ('L4', models.FloatField(blank=True, null=True)),
                ('D4', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToolAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_nr', models.IntegerField()),
                ('radius', models.FloatField()),
                ('total_length', models.FloatField()),
                ('outside_holder', models.FloatField()),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_assembly.holder')),
                ('machine', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tools', to='machines.machine')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_assembly.tool')),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('toolassembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tools_assembly.toolassembly')),
            ],
        ),
    ]
