# Generated by Django 4.2.3 on 2023-08-07 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_type', models.CharField(choices=[('type_1', 'SLIM_100'), ('type_2', 'SLIM_150'), ('type_3', 'SLIM_200'), ('type_4', 'TERMO_100'), ('type_5', 'TERMO_150'), ('type_6', 'TERMO_200'), ('type_7', 'ER_32'), ('type_8', 'ER_40'), ('type_9', 'WELDON_100'), ('type_10', 'WELDON_150'), ('type_11', 'WELDON_200'), ('type_12', 'STYROPIAN'), ('type_13', 'UCHWYT_76')], max_length=100)),
                ('inner_diameter', models.PositiveIntegerField()),
                ('catalog_nr', models.CharField(blank=True, max_length=100)),
                ('LH1', models.FloatField(blank=True, null=True)),
                ('DH1_A', models.FloatField(blank=True, null=True)),
                ('DH1_B', models.FloatField(blank=True, null=True)),
                ('LH2', models.FloatField(blank=True, null=True)),
                ('DH2', models.FloatField(blank=True, null=True)),
                ('LH3', models.FloatField(blank=True, null=True)),
                ('DH3', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(max_length=100)),
                ('catalog_nr', models.CharField(max_length=100)),
                ('L1', models.FloatField()),
                ('D1', models.FloatField()),
                ('L2', models.FloatField()),
                ('D2', models.FloatField()),
                ('L3', models.FloatField()),
                ('D3', models.FloatField()),
                ('L4', models.FloatField()),
                ('D4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ToolAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_nr', models.IntegerField()),
                ('radius', models.FloatField()),
                ('total_length', models.FloatField()),
                ('outside_holder', models.FloatField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_assembly.holder')),
                ('machine', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tools', to='machines.machine')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_assembly.tool')),
            ],
        ),
    ]
