# Generated by Django 4.2.3 on 2023-08-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_assembly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='R',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(choices=[('end_mill', 'WALEC'), ('ball_nose', 'KULA'), ('bull_nose', 'WALEC_Z_R'), ('typer_ball_nose', 'STOZKOWY'), ('engraving', 'GRAWERKA'), ('drill', 'WIERTŁO')], max_length=100),
        ),
    ]
