# Generated by Django 4.2.3 on 2023-09-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        ('holders', '0001_initial'),
        ('tools_assembly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='author',
        ),
        migrations.AlterField(
            model_name='toolassembly',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holders.holder'),
        ),
        migrations.AlterField(
            model_name='toolassembly',
            name='outside_holder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='toolassembly',
            name='radius',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='toolassembly',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool'),
        ),
        migrations.AlterField(
            model_name='toolassembly',
            name='total_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Holder',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
