# Generated by Django 4.2.3 on 2023-10-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        ('tools_assembly', '0003_alter_toolassembly_tool_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolassembly',
            name='machine',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tools', to='machines.machine'),
        ),
    ]
