# Generated by Django 4.2.3 on 2024-03-14 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools_assembly", "0007_alter_toolassembly_author_alter_toolassembly_holder_and_more"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="Comment creation date"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False, help_text="Notification status"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                help_text="Author of the notification",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user_comment",
            field=models.ForeignKey(
                help_text="User comment", on_delete=django.db.models.deletion.CASCADE, to="tools_assembly.usercomment"
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="is_read",
            field=models.BooleanField(default=False, help_text="User notification status"),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="notification",
            field=models.ForeignKey(
                help_text="Notification sent to users",
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.notification",
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="user",
            field=models.ForeignKey(
                help_text="Author of the user notification",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
